export const EventTypes = {
  GAME: {
    START: "GAME:START",
    PAUSE: "GAME:PAUSE",
    RESUME: "GAME:RESUME",
    OVER: "GAME:OVER",
    WIN: "GAME:WIN",
  },
  ASSETS: {
    LOADED: "ASSETS:LOADED",
    ERROR: "ASSETS:ERROR",
  },
  UI: {
    OPEN_PANEL: "UI:OPEN_PANEL",
    CLOSE_PANEL: "UI:CLOSE_PANEL",
    BUTTON_CLICK: "UI:BUTTON_CLICK",
  },
  PLAYER: {
    MOVE: "PLAYER:MOVE",
    ACTION: "PLAYER:ACTION",
    DAMAGE: "PLAYER:DAMAGE",
    DEATH: "PLAYER:DEATH",
  },
  FARM: {
    PLANT: "FARM:PLANT",
    HARVEST: "FARM:HARVEST",
    UPGRADE: "FARM:UPGRADE",
  },
  DAY: {
    DAWN: "DAY:DAWN",
    DUSK: "DAY:DUSK",
    NEXT_DAY: "DAY:NEXT_DAY",
    HOUR_CHANGED: "DAY:HOUR_CHANGED",
    TIME_UPDATE: "DAY:TIME_UPDATE",
  },
};
